<?php
/**
 * Campos editáveis da página "Canal de Denúncia" (page-canal-denuncia.php).
 * Mesmo padrão da Home: abas por seção, cada campo já preenchido com o texto
 * atual (default_value), então o cliente vê o conteúdo de hoje e só edita o
 * que quiser. Prefixo "canal-denuncia_" para não colidir com outras páginas.
 */
if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

acf_add_local_field_group( [
    'key'    => 'group_canal-denuncia',
    'title'  => 'Conteúdo: Canal de Denúncia',
    'fields' => [

        // ───────────── TOPO ─────────────
        [ 'key' => 'tab_canal-denuncia_topo', 'label' => 'Topo', 'type' => 'tab' ],
        [
            'key'           => 'field_canal-denuncia_hero_titulo1',
            'label'         => 'Título do topo — linha 1',
            'name'          => 'canal-denuncia_hero_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título grande (cor preta).',
            'default_value' => 'Canal de',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_titulo2',
            'label'         => 'Título do topo — linha 2 (verde)',
            'name'          => 'canal-denuncia_hero_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título (cor verde).',
            'default_value' => 'denúncia',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_titulo3',
            'label'         => 'Título do topo — linha 3 (itálico cinza)',
            'name'          => 'canal-denuncia_hero_titulo3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha do título (itálico, cinza claro).',
            'default_value' => 'e ética.',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_cta',
            'label'         => 'Rótulo do botão do topo',
            'name'          => 'canal-denuncia_hero_cta',
            'type'          => 'text',
            'instructions'  => 'Texto do botão verde abaixo do título (leva ao formulário).',
            'default_value' => 'Registrar uma denúncia',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_intro',
            'label'         => 'Texto de apresentação do topo',
            'name'          => 'canal-denuncia_hero_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Parágrafo à direita do título, explicando o canal.',
            'default_value' => 'Um espaço seguro para relatar, de forma confidencial e anônima, condutas que violem nosso código de ética, valores ou a legislação.',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_dl1_rotulo',
            'label'         => 'Ficha do topo — rótulo 1',
            'name'          => 'canal-denuncia_hero_dl1_rotulo',
            'type'          => 'text',
            'instructions'  => 'Primeiro rótulo da pequena ficha (canto direito).',
            'default_value' => 'Sigilo',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_dl1_valor',
            'label'         => 'Ficha do topo — valor 1',
            'name'          => 'canal-denuncia_hero_dl1_valor',
            'type'          => 'text',
            'instructions'  => 'Valor correspondente ao rótulo "Sigilo".',
            'default_value' => '100% confidencial',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_dl2_rotulo',
            'label'         => 'Ficha do topo — rótulo 2',
            'name'          => 'canal-denuncia_hero_dl2_rotulo',
            'type'          => 'text',
            'instructions'  => 'Segundo rótulo da pequena ficha (canto direito).',
            'default_value' => 'Identificação',
        ],
        [
            'key'           => 'field_canal-denuncia_hero_dl2_valor',
            'label'         => 'Ficha do topo — valor 2',
            'name'          => 'canal-denuncia_hero_dl2_valor',
            'type'          => 'text',
            'instructions'  => 'Valor correspondente ao rótulo "Identificação".',
            'default_value' => 'Anônima (opcional)',
        ],
        [
            'key'           => 'field_canal-denuncia_foto_alt',
            'label'         => 'Texto alternativo da foto (faixa P&B)',
            'name'          => 'canal-denuncia_foto_alt',
            'type'          => 'text',
            'instructions'  => 'Descrição da imagem (acessibilidade). Não aparece visualmente.',
            'default_value' => 'Conduta ética e relações de boa-fé na JOB Engenharia',
        ],

        // ───────────── COMO FUNCIONA ─────────────
        [ 'key' => 'tab_canal-denuncia_funciona', 'label' => 'Como funciona', 'type' => 'tab' ],
        [
            'key'           => 'field_canal-denuncia_funciona_chip',
            'label'         => 'Etiqueta da seção',
            'name'          => 'canal-denuncia_funciona_chip',
            'type'          => 'text',
            'instructions'  => 'Pequeno rótulo verde acima do título da seção.',
            'default_value' => 'Como funciona',
        ],
        [
            'key'           => 'field_canal-denuncia_funciona_titulo1',
            'label'         => 'Título da seção — linha 1',
            'name'          => 'canal-denuncia_funciona_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título (cor preta).',
            'default_value' => 'Sua manifestação é',
        ],
        [
            'key'           => 'field_canal-denuncia_funciona_titulo2',
            'label'         => 'Título da seção — linha 2 (itálico cinza)',
            'name'          => 'canal-denuncia_funciona_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título (itálico, cinza claro).',
            'default_value' => 'levada a sério.',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge1_titulo',
            'label'         => '01 · Confidencialidade — título',
            'name'          => 'canal-denuncia_pledge1_titulo',
            'type'          => 'text',
            'instructions'  => 'Título da garantia 01.',
            'default_value' => 'Confidencialidade garantida',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge1_desc',
            'label'         => '01 · Confidencialidade — descrição',
            'name'          => 'canal-denuncia_pledge1_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Texto da garantia "Confidencialidade garantida".',
            'default_value' => 'Todas as informações são tratadas com sigilo e analisadas por um comitê responsável, conforme nossa Política de Privacidade e a LGPD.',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge2_titulo',
            'label'         => '02 · Anonimato — título',
            'name'          => 'canal-denuncia_pledge2_titulo',
            'type'          => 'text',
            'instructions'  => 'Título da garantia 02.',
            'default_value' => 'Anonimato, se você preferir',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge2_desc',
            'label'         => '02 · Anonimato — descrição',
            'name'          => 'canal-denuncia_pledge2_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Texto da garantia "Anonimato, se você preferir".',
            'default_value' => 'Você decide se quer se identificar. O relato anônimo é aceito e apurado da mesma forma — a identificação apenas facilita o retorno e o esclarecimento de dúvidas.',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge3_titulo',
            'label'         => '03 · Não retaliação — título',
            'name'          => 'canal-denuncia_pledge3_titulo',
            'type'          => 'text',
            'instructions'  => 'Título da garantia 03.',
            'default_value' => 'Não retaliação',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge3_desc',
            'label'         => '03 · Não retaliação — descrição',
            'name'          => 'canal-denuncia_pledge3_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Texto da garantia "Não retaliação".',
            'default_value' => 'É proibida qualquer forma de retaliação contra quem relata de boa-fé. Use este canal de maneira responsável e verdadeira.',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge4_titulo',
            'label'         => '04 · O que pode ser relatado — título',
            'name'          => 'canal-denuncia_pledge4_titulo',
            'type'          => 'text',
            'instructions'  => 'Título da garantia 04.',
            'default_value' => 'O que pode ser relatado',
        ],
        [
            'key'           => 'field_canal-denuncia_pledge4_desc',
            'label'         => '04 · O que pode ser relatado — descrição',
            'name'          => 'canal-denuncia_pledge4_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Texto da garantia "O que pode ser relatado".',
            'default_value' => 'Assédio, discriminação, fraude, corrupção, conflito de interesses, desvios de conduta, questões ambientais, de saúde e segurança, entre outras violações.',
        ],

        // ───────────── FORMULÁRIO (textos de apoio) ─────────────
        [ 'key' => 'tab_canal-denuncia_form', 'label' => 'Formulário', 'type' => 'tab' ],
        [
            'key'           => 'field_canal-denuncia_form_titulo1',
            'label'         => 'Título do formulário — linha 1',
            'name'          => 'canal-denuncia_form_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título da coluna lateral.',
            'default_value' => 'Registrar',
        ],
        [
            'key'           => 'field_canal-denuncia_form_titulo2',
            'label'         => 'Título do formulário — linha 2 (com destaque)',
            'name'          => 'canal-denuncia_form_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha: texto antes da palavra destacada em itálico.',
            'default_value' => 'uma',
        ],
        [
            'key'           => 'field_canal-denuncia_form_titulo3',
            'label'         => 'Título do formulário — palavra destacada (itálico)',
            'name'          => 'canal-denuncia_form_titulo3',
            'type'          => 'text',
            'instructions'  => 'Palavra final do título, em itálico cinza.',
            'default_value' => 'denúncia.',
        ],
        [
            'key'           => 'field_canal-denuncia_form_intro',
            'label'         => 'Instrução principal do formulário',
            'name'          => 'canal-denuncia_form_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Parágrafo na coluna lateral pedindo detalhes do ocorrido.',
            'default_value' => 'Descreva o ocorrido com o máximo de detalhes possível: o que aconteceu, quem esteve envolvido, quando e onde. Quanto mais informações, melhor a apuração.',
        ],
        [
            'key'           => 'field_canal-denuncia_form_importante_rotulo',
            'label'         => 'Rótulo "Importante"',
            'name'          => 'canal-denuncia_form_importante_rotulo',
            'type'          => 'text',
            'instructions'  => 'Pequeno rótulo verde acima do aviso de emergência.',
            'default_value' => 'Importante',
        ],
        [
            'key'           => 'field_canal-denuncia_form_importante',
            'label'         => 'Aviso "Importante"',
            'name'          => 'canal-denuncia_form_importante',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Texto do bloco "Importante" sobre emergências (190 / 193).',
            'default_value' => 'Este canal destina-se a relatos de conduta. Para emergências, risco iminente à vida ou crimes em andamento, acione imediatamente as autoridades competentes (190 / 193).',
        ],
        [
            'key'           => 'field_canal-denuncia_form_cabecalho_titulo',
            'label'         => 'Cabeçalho do formulário — título',
            'name'          => 'canal-denuncia_form_cabecalho_titulo',
            'type'          => 'text',
            'instructions'  => 'Título dentro do quadro branco do formulário.',
            'default_value' => 'Formulário de denúncia',
        ],
        [
            'key'           => 'field_canal-denuncia_btn_enviar',
            'label'         => 'Rótulo do botão de envio',
            'name'          => 'canal-denuncia_btn_enviar',
            'type'          => 'text',
            'instructions'  => 'Texto do botão preto que envia a denúncia.',
            'default_value' => 'Enviar denúncia',
        ],

    ],
    'location' => [ [ [
        'param'    => 'page',
        'operator' => '==',
        'value'    => 11,
    ] ] ],
    'menu_order'            => 0,
    'position'              => 'normal',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
] );
