<?php
/**
 * Campos editáveis da página "Trabalhe Conosco" (page-carreiras.php).
 * Organizados em abas por seção. Cada campo já vem preenchido com o texto
 * atual (default_value), então o cliente vê o conteúdo de hoje e só edita
 * o que quiser. Tudo prefixado com carreiras_ para não colidir com outras páginas.
 */
if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

acf_add_local_field_group( [
    'key'    => 'group_carreiras',
    'title'  => 'Conteúdo: Trabalhe Conosco',
    'fields' => [

        [ 'key' => 'tab_carreiras_topo', 'label' => 'Topo', 'type' => 'tab' ],
        [
            'key'           => 'field_carreiras_hero_titulo1',
            'label'         => 'Título principal — Linha 1',
            'name'          => 'carreiras_hero_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título grande do topo.',
            'default_value' => 'Construa sua',
        ],
        [
            'key'           => 'field_carreiras_hero_titulo2',
            'label'         => 'Título principal — Linha 2 (início)',
            'name'          => 'carreiras_hero_titulo2',
            'type'          => 'text',
            'instructions'  => 'Início da segunda linha do título (texto preto, antes da parte verde).',
            'default_value' => 'carreira',
        ],
        [
            'key'           => 'field_carreiras_hero_titulo3',
            'label'         => 'Título principal — Linha 2 (destaque verde)',
            'name'          => 'carreiras_hero_titulo3',
            'type'          => 'text',
            'instructions'  => 'Parte em verde no fim do título. Mantém a cor verde no site.',
            'default_value' => 'na JOB',
        ],
        [
            'key'           => 'field_carreiras_hero_sub',
            'label'         => 'Texto do topo',
            'name'          => 'carreiras_hero_sub',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Parágrafo curto ao lado do título principal.',
            'default_value' => 'Buscamos profissionais que desejam fazer parte de uma empresa que gere resultados, com cultura técnica e projetos relevantes.',
        ],
        [
            'key'           => 'field_carreiras_foto_alt',
            'label'         => 'Descrição da foto (cultura e equipe)',
            'name'          => 'carreiras_foto_alt',
            'type'          => 'text',
            'instructions'  => 'Texto alternativo da foto de cultura/equipe (acessibilidade e SEO). Não aparece visualmente.',
            'default_value' => 'Equipe da JOB Engenharia em campo — cultura técnica e colaborativa',
        ],

        [ 'key' => 'tab_carreiras_porque', 'label' => 'Por que a JOB', 'type' => 'tab' ],
        [
            'key'           => 'field_carreiras_porque_titulo1',
            'label'         => 'Título da seção — Linha 1',
            'name'          => 'carreiras_porque_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título (texto preto).',
            'default_value' => 'Engenharia',
        ],
        [
            'key'           => 'field_carreiras_porque_titulo2a',
            'label'         => 'Título da seção — Linha 2 (início)',
            'name'          => 'carreiras_porque_titulo2a',
            'type'          => 'text',
            'instructions'  => 'Início da segunda linha (texto preto, antes da parte verde).',
            'default_value' => 'e',
        ],
        [
            'key'           => 'field_carreiras_porque_titulo2b',
            'label'         => 'Título da seção — Linha 2 (destaque verde)',
            'name'          => 'carreiras_porque_titulo2b',
            'type'          => 'text',
            'instructions'  => 'Parte em verde da segunda linha. Mantém a cor verde no site.',
            'default_value' => 'cultura',
        ],
        [
            'key'           => 'field_carreiras_porque_titulo3',
            'label'         => 'Título da seção — Linha 3 (itálico)',
            'name'          => 'carreiras_porque_titulo3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha do título, em itálico/cinza. Mantém o estilo no site.',
            'default_value' => 'técnica.',
        ],
        [
            'key'           => 'field_carreiras_porque_intro',
            'label'         => 'Texto de apresentação da seção',
            'name'          => 'carreiras_porque_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Parágrafo ao lado do título "Engenharia e cultura técnica".',
            'default_value' => 'Mais de quatro décadas operando em campo. Trabalho técnico relevante, com investimento contínuo no desenvolvimento das equipes.',
        ],
        [
            'key'           => 'field_carreiras_pilar1_titulo',
            'label'         => 'Pilar 1 — Título',
            'name'          => 'carreiras_pilar1_titulo',
            'type'          => 'text',
            'instructions'  => 'Subtítulo do primeiro pilar.',
            'default_value' => 'Mais de 40 anos em campo',
        ],
        [
            'key'           => 'field_carreiras_pilar1_texto',
            'label'         => 'Pilar 1 — Texto',
            'name'          => 'carreiras_pilar1_texto',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Empresa consolidada, com cultura técnica forte e atuação que gera impacto real e valor duradouro para a sociedade.',
        ],
        [
            'key'           => 'field_carreiras_pilar2_titulo',
            'label'         => 'Pilar 2 — Título',
            'name'          => 'carreiras_pilar2_titulo',
            'type'          => 'text',
            'instructions'  => 'Subtítulo do segundo pilar.',
            'default_value' => 'Atuação multidisciplinar',
        ],
        [
            'key'           => 'field_carreiras_pilar2_texto',
            'label'         => 'Pilar 2 — Texto',
            'name'          => 'carreiras_pilar2_texto',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Ambiente dinâmico, com diversidade de serviços e tecnologias que proporcionam aprendizado contínuo e crescimento profissional.',
        ],
        [
            'key'           => 'field_carreiras_pilar3_titulo',
            'label'         => 'Pilar 3 — Título',
            'name'          => 'carreiras_pilar3_titulo',
            'type'          => 'text',
            'instructions'  => 'Subtítulo do terceiro pilar.',
            'default_value' => 'Compromisso com pessoas',
        ],
        [
            'key'           => 'field_carreiras_pilar3_texto',
            'label'         => 'Pilar 3 — Texto',
            'name'          => 'carreiras_pilar3_texto',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Valorização técnica, ambiente colaborativo e oportunidades reais de desenvolvimento profissional.',
        ],

        [ 'key' => 'tab_carreiras_vagas', 'label' => 'Chamada de vagas', 'type' => 'tab' ],
        [
            'key'           => 'field_carreiras_vagas_titulo1',
            'label'         => 'Título da chamada — Linha 1',
            'name'          => 'carreiras_vagas_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título (texto branco).',
            'default_value' => 'Confira as vagas',
        ],
        [
            'key'           => 'field_carreiras_vagas_titulo2',
            'label'         => 'Título da chamada — Linha 2 (itálico verde-claro)',
            'name'          => 'carreiras_vagas_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título, em itálico e verde-claro. Mantém o estilo no site.',
            'default_value' => 'disponíveis.',
        ],
        [
            'key'           => 'field_carreiras_vagas_texto',
            'label'         => 'Texto da chamada de vagas',
            'name'          => 'carreiras_vagas_texto',
            'type'          => 'textarea',
            'rows'          => 2,
            'instructions'  => 'Parágrafo abaixo do título "Confira as vagas disponíveis".',
            'default_value' => 'Acesse nossa página de oportunidades e descubra como fazer parte da nossa equipe.',
        ],
        [
            'key'           => 'field_carreiras_vagas_botao',
            'label'         => 'Texto do botão de vagas',
            'name'          => 'carreiras_vagas_botao',
            'type'          => 'text',
            'instructions'  => 'Rótulo do botão (CTA). Frase curta.',
            'default_value' => 'Ver vagas disponíveis',
        ],

    ],
    'location' => [ [ [
        'param'    => 'page',
        'operator' => '==',
        'value'    => 10,
    ] ] ],
    'menu_order'            => 0,
    'position'              => 'normal',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
] );
