<?php
/**
 * Campos editáveis da página Ecojob (page-ecojob.php).
 * Organizados em abas por seção. Cada campo já vem preenchido com o
 * texto atual (default_value), então o cliente vê o conteúdo de hoje
 * e só edita o que quiser. Tudo prefixado com ecojob_ para não colidir
 * com outras páginas.
 */
if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

acf_add_local_field_group( [
    'key'    => 'group_ecojob',
    'title'  => 'Conteúdo: Ecojob',
    'fields' => [

        [ 'key' => 'tab_ecojob_topo', 'label' => 'Topo', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_hero_titulo1',
            'label'         => 'Título — linha 1 (fina)',
            'name'          => 'ecojob_hero_titulo1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título principal (fonte fina).',
            'default_value' => 'Tecnologia, inteligência',
        ],
        [
            'key'           => 'field_ecojob_hero_titulo2',
            'label'         => 'Título — linha 2 (forte)',
            'name'          => 'ecojob_hero_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título principal (fonte forte).',
            'default_value' => 'e operação para',
        ],
        [
            'key'           => 'field_ecojob_hero_titulo3',
            'label'         => 'Título — linha 3 (forte)',
            'name'          => 'ecojob_hero_titulo3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha do título principal (fonte forte).',
            'default_value' => 'sistemas ambientais.',
        ],
        [
            'key'           => 'field_ecojob_hero_intro',
            'label'         => 'Texto de apresentação (topo)',
            'name'          => 'ecojob_hero_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Parágrafo ao lado do título principal. Você pode usar <strong>negrito</strong> em HTML.',
            'default_value' => 'A <strong style="font-weight:700;">Ecojob</strong> desenvolve soluções integradas e tecnológicas para sistemas ambientais, saneamento e recursos hídricos, transformando dados em inteligência operacional.',
        ],
        [
            'key'           => 'field_ecojob_hero_anc1',
            'label'         => 'Atalho 1 (faixa de botões)',
            'name'          => 'ecojob_hero_anc1',
            'type'          => 'text',
            'instructions'  => 'Rótulo do 1º atalho. Não altera o link, apenas o texto.',
            'default_value' => 'Engenharia diagnóstica',
        ],
        [
            'key'           => 'field_ecojob_hero_anc2',
            'label'         => 'Atalho 2 (faixa de botões)',
            'name'          => 'ecojob_hero_anc2',
            'type'          => 'text',
            'default_value' => 'Monitoramento inteligente',
        ],
        [
            'key'           => 'field_ecojob_hero_anc3',
            'label'         => 'Atalho 3 (faixa de botões)',
            'name'          => 'ecojob_hero_anc3',
            'type'          => 'text',
            'default_value' => 'Modelagem hidrológica',
        ],
        [
            'key'           => 'field_ecojob_hero_anc4',
            'label'         => 'Atalho 4 (faixa de botões)',
            'name'          => 'ecojob_hero_anc4',
            'type'          => 'text',
            'default_value' => 'Operação e gestão',
        ],
        [
            'key'           => 'field_ecojob_hero_anc5',
            'label'         => 'Atalho 5 (faixa de botões)',
            'name'          => 'ecojob_hero_anc5',
            'type'          => 'text',
            'default_value' => 'Plataforma COI 4.0',
        ],
        [
            'key'           => 'field_ecojob_faixa_chip',
            'label'         => 'Faixa de imagem — rótulo',
            'name'          => 'ecojob_faixa_chip',
            'type'          => 'text',
            'instructions'  => 'Pequeno rótulo verde sobre a foto.',
            'default_value' => 'Monitoramento ambiental',
        ],
        [
            'key'           => 'field_ecojob_faixa_legenda',
            'label'         => 'Faixa de imagem — legenda',
            'name'          => 'ecojob_faixa_legenda',
            'type'          => 'text',
            'instructions'  => 'Frase sobre a foto.',
            'default_value' => 'Coleta e análise da qualidade da água em campo.',
        ],

        [ 'key' => 'tab_ecojob_abertura', 'label' => 'Abertura', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_abertura_destaque',
            'label'         => 'Texto de destaque (esquerda)',
            'name'          => 'ecojob_abertura_destaque',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Parágrafo grande de abertura da página.',
            'default_value' => 'Atuamos de forma integrada no monitoramento ambiental, modelagem hidráulica e hidrológica, supervisão operacional e gestão de infraestruturas críticas, combinando engenharia, tecnologia e inteligência de dados para apoiar a tomada de decisão e otimizar o desempenho dos sistemas.',
        ],
        [
            'key'           => 'field_ecojob_abertura_texto',
            'label'         => 'Texto complementar (direita)',
            'name'          => 'ecojob_abertura_texto',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Nossas soluções contribuem para operações mais eficientes, seguras e sustentáveis, atendendo aos desafios atuais e futuros da infraestrutura ambiental.',
        ],

        [ 'key' => 'tab_ecojob_diagnostica', 'label' => 'Eng. diagnóstica', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_diagnostica_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_diagnostica_titulo1',
            'type'          => 'text',
            'default_value' => 'Engenharia',
        ],
        [
            'key'           => 'field_ecojob_diagnostica_titulo2',
            'label'         => 'Título — linha 2 (verde)',
            'name'          => 'ecojob_diagnostica_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha, exibida em verde.',
            'default_value' => 'diagnóstica.',
        ],
        [
            'key'           => 'field_ecojob_diagnostica_intro',
            'label'         => 'Texto de apresentação',
            'name'          => 'ecojob_diagnostica_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Realizamos diagnósticos técnicos detalhados para identificar anomalias, avaliar o desempenho das infraestruturas e subsidiar a definição de ações corretivas e preventivas.',
        ],
        [
            'key'           => 'field_ecojob_diag_card1_titulo',
            'label'         => 'Card 1 — título',
            'name'          => 'ecojob_diag_card1_titulo',
            'type'          => 'text',
            'default_value' => 'Varredura e Rastreamento Operacional',
        ],
        [
            'key'           => 'field_ecojob_diag_card1_desc',
            'label'         => 'Card 1 — descrição',
            'name'          => 'ecojob_diag_card1_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Inspeções e rastreamentos operacionais para avaliação das redes, identificação de gargalos, interferências, lançamentos irregulares e não conformidades.',
        ],
        [
            'key'           => 'field_ecojob_diag_card2_titulo',
            'label'         => 'Card 2 — título',
            'name'          => 'ecojob_diag_card2_titulo',
            'type'          => 'text',
            'default_value' => 'Testes de Fumaça e Corante',
        ],
        [
            'key'           => 'field_ecojob_diag_card2_desc',
            'label'         => 'Card 2 — descrição',
            'name'          => 'ecojob_diag_card2_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Metodologias especializadas para identificação de ligações clandestinas, descartes irregulares, interconexões indevidas entre redes e falhas de vedação, permitindo rastrear o percurso e o destino dos fluxos.',
        ],
        [
            'key'           => 'field_ecojob_diag_card3_titulo',
            'label'         => 'Card 3 — título',
            'name'          => 'ecojob_diag_card3_titulo',
            'type'          => 'text',
            'default_value' => 'Mapeamento complementar com drones',
        ],
        [
            'key'           => 'field_ecojob_diag_card3_desc',
            'label'         => 'Card 3 — descrição',
            'name'          => 'ecojob_diag_card3_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Inspeções aéreas e monitoramento de áreas e estruturas de difícil acesso, com registro de anomalias e geração de informações georreferenciadas para apoio aos diagnósticos.',
        ],
        [
            'key'           => 'field_ecojob_diag_card4_titulo',
            'label'         => 'Card 4 — título',
            'name'          => 'ecojob_diag_card4_titulo',
            'type'          => 'text',
            'default_value' => 'Inspeção por CFTV',
        ],
        [
            'key'           => 'field_ecojob_diag_card4_desc',
            'label'         => 'Card 4 — descrição',
            'name'          => 'ecojob_diag_card4_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Inspeções internas por circuito fechado de televisão (CFTV), utilizando métodos não destrutivos para avaliação das condições operacionais, estruturais e hidráulicas das redes.',
        ],

        [ 'key' => 'tab_ecojob_monitoramento', 'label' => 'Monitoramento', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_monit_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_monit_titulo1',
            'type'          => 'text',
            'default_value' => 'Monitoramento inteligente',
        ],
        [
            'key'           => 'field_ecojob_monit_titulo2',
            'label'         => 'Título — linha 2 (verde)',
            'name'          => 'ecojob_monit_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha, exibida em verde.',
            'default_value' => 'de sistemas.',
        ],
        [
            'key'           => 'field_ecojob_monitoramento_intro',
            'label'         => 'Texto de apresentação',
            'name'          => 'ecojob_monitoramento_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Por meio de sensoriamento avançado, telemetria e análise de dados, realizamos o monitoramento contínuo e em tempo real de sistemas ambientais e de saneamento, apoiando a gestão e a tomada de decisão baseada em dados.',
        ],
        [
            'key'           => 'field_ecojob_monit_param_label',
            'label'         => 'Rótulo — Parâmetros monitorados',
            'name'          => 'ecojob_monit_param_label',
            'type'          => 'text',
            'default_value' => 'Parâmetros monitorados',
        ],
        [
            'key'           => 'field_ecojob_monit_chip1',
            'label'         => 'Parâmetro 1',
            'name'          => 'ecojob_monit_chip1',
            'type'          => 'text',
            'default_value' => 'Nível',
        ],
        [
            'key'           => 'field_ecojob_monit_chip2',
            'label'         => 'Parâmetro 2',
            'name'          => 'ecojob_monit_chip2',
            'type'          => 'text',
            'default_value' => 'Vazão',
        ],
        [
            'key'           => 'field_ecojob_monit_chip3',
            'label'         => 'Parâmetro 3',
            'name'          => 'ecojob_monit_chip3',
            'type'          => 'text',
            'default_value' => 'pH',
        ],
        [
            'key'           => 'field_ecojob_monit_chip4',
            'label'         => 'Parâmetro 4',
            'name'          => 'ecojob_monit_chip4',
            'type'          => 'text',
            'default_value' => 'Condutividade',
        ],
        [
            'key'           => 'field_ecojob_monit_chip5',
            'label'         => 'Parâmetro 5',
            'name'          => 'ecojob_monit_chip5',
            'type'          => 'text',
            'default_value' => 'Temperatura',
        ],
        [
            'key'           => 'field_ecojob_monit_chip6',
            'label'         => 'Parâmetro 6',
            'name'          => 'ecojob_monit_chip6',
            'type'          => 'text',
            'default_value' => 'Carga poluidora',
        ],
        [
            'key'           => 'field_ecojob_monit_chip7',
            'label'         => 'Parâmetro 7',
            'name'          => 'ecojob_monit_chip7',
            'type'          => 'text',
            'default_value' => 'DBO',
        ],
        [
            'key'           => 'field_ecojob_monit_chip8',
            'label'         => 'Parâmetro 8',
            'name'          => 'ecojob_monit_chip8',
            'type'          => 'text',
            'default_value' => 'OD',
        ],
        [
            'key'           => 'field_ecojob_monit_chip9',
            'label'         => 'Parâmetro 9',
            'name'          => 'ecojob_monit_chip9',
            'type'          => 'text',
            'default_value' => 'Turbidez',
        ],
        [
            'key'           => 'field_ecojob_monit_card1_titulo',
            'label'         => 'Card 1 — título',
            'name'          => 'ecojob_monit_card1_titulo',
            'type'          => 'text',
            'default_value' => 'Efluentes e esgotamento sanitário',
        ],
        [
            'key'           => 'field_ecojob_monit_card1_desc',
            'label'         => 'Card 1 — descrição',
            'name'          => 'ecojob_monit_card1_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Monitoramento contínuo e em tempo real de efluentes e do sistema de esgotamento sanitário, acompanhando vazão, carga poluidora e demais indicadores para apoiar a operação e a conformidade ambiental.',
        ],
        [
            'key'           => 'field_ecojob_monit_card2_titulo',
            'label'         => 'Card 2 — título',
            'name'          => 'ecojob_monit_card2_titulo',
            'type'          => 'text',
            'default_value' => 'Córregos, rios, canais e balneabilidade',
        ],
        [
            'key'           => 'field_ecojob_monit_card2_desc',
            'label'         => 'Card 2 — descrição',
            'name'          => 'ecojob_monit_card2_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Monitoramento da qualidade da água em córregos, rios e canais, com acompanhamento de parâmetros físico-químicos e avaliação da balneabilidade para a proteção dos corpos hídricos.',
        ],
        [
            'key'           => 'field_ecojob_monit_card3_titulo',
            'label'         => 'Card 3 — título',
            'name'          => 'ecojob_monit_card3_titulo',
            'type'          => 'text',
            'default_value' => 'Sistemas de drenagem',
        ],
        [
            'key'           => 'field_ecojob_monit_card3_desc',
            'label'         => 'Card 3 — descrição',
            'name'          => 'ecojob_monit_card3_desc',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Monitoramento de sistemas de drenagem com sensoriamento de nível e telemetria, identificando variações anômalas de nível e vazão para apoiar a prevenção de alagamentos.',
        ],
        [
            'key'           => 'field_ecojob_monit_card4_titulo',
            'label'         => 'Card 4 — título',
            'name'          => 'ecojob_monit_card4_titulo',
            'type'          => 'text',
            'default_value' => 'Medição de dados meteorológicos',
        ],
        [
            'key'           => 'field_ecojob_monit_card4_desc',
            'label'         => 'Card 4 — descrição',
            'name'          => 'ecojob_monit_card4_desc',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Estações meteorológicas inteligentes integradas a sistemas IoT e comunicação via satélite para monitoramento contínuo de precipitação, temperatura, umidade, pressão atmosférica e ventos, apoiando a avaliação de riscos e o planejamento operacional.',
        ],
        [
            'key'           => 'field_ecojob_monit_card5_titulo',
            'label'         => 'Card 5 — título',
            'name'          => 'ecojob_monit_card5_titulo',
            'type'          => 'text',
            'default_value' => 'Análise geoespacial e mapas de calor (Kernel)',
        ],
        [
            'key'           => 'field_ecojob_monit_card5_desc',
            'label'         => 'Card 5 — descrição',
            'name'          => 'ecojob_monit_card5_desc',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Estudo integrado de dados históricos, georreferenciados, topográficos e meteorológicos para a geração de mapas de calor (Kernel), identificando pontos críticos de recorrência, áreas suscetíveis a acúmulo e regiões prioritárias para atuação.',
        ],

        [ 'key' => 'tab_ecojob_modelagem', 'label' => 'Modelagem', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_model_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_model_titulo1',
            'type'          => 'text',
            'default_value' => 'Modelagem hidráulica',
        ],
        [
            'key'           => 'field_ecojob_model_titulo2',
            'label'         => 'Título — linha 2 (verde)',
            'name'          => 'ecojob_model_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha, exibida em verde.',
            'default_value' => 'e hidrológica.',
        ],
        [
            'key'           => 'field_ecojob_modelagem_intro',
            'label'         => 'Texto de apresentação',
            'name'          => 'ecojob_modelagem_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Desenvolvemos modelos hidráulicos e hidrológicos para compreender o comportamento de redes e sistemas ambientais, avaliando sua resposta a diferentes condições de operação e eventos críticos. As simulações permitem analisar cenários, identificar vulnerabilidades e apoiar o planejamento de intervenções, ampliações e investimentos.',
        ],
        [
            'key'           => 'field_ecojob_model_item1_titulo',
            'label'         => 'Item 1 — título',
            'name'          => 'ecojob_model_item1_titulo',
            'type'          => 'text',
            'default_value' => 'Análise de cenários',
        ],
        [
            'key'           => 'field_ecojob_model_item1_desc',
            'label'         => 'Item 1 — descrição',
            'name'          => 'ecojob_model_item1_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Simulação do comportamento das redes sob diferentes condições de operação e eventos críticos.',
        ],
        [
            'key'           => 'field_ecojob_model_item2_titulo',
            'label'         => 'Item 2 — título',
            'name'          => 'ecojob_model_item2_titulo',
            'type'          => 'text',
            'default_value' => 'Identificação de vulnerabilidades',
        ],
        [
            'key'           => 'field_ecojob_model_item2_desc',
            'label'         => 'Item 2 — descrição',
            'name'          => 'ecojob_model_item2_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Mapeamento de gargalos e pontos frágeis que comprometem o desempenho dos sistemas.',
        ],
        [
            'key'           => 'field_ecojob_model_item3_titulo',
            'label'         => 'Item 3 — título',
            'name'          => 'ecojob_model_item3_titulo',
            'type'          => 'text',
            'default_value' => 'Planejamento de investimentos',
        ],
        [
            'key'           => 'field_ecojob_model_item3_desc',
            'label'         => 'Item 3 — descrição',
            'name'          => 'ecojob_model_item3_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Suporte técnico ao planejamento de intervenções, ampliações e priorização de obras.',
        ],

        [ 'key' => 'tab_ecojob_operacao', 'label' => 'Operação', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_oper_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_oper_titulo1',
            'type'          => 'text',
            'default_value' => 'Operação, supervisão',
        ],
        [
            'key'           => 'field_ecojob_oper_titulo2',
            'label'         => 'Título — destaque verde',
            'name'          => 'ecojob_oper_titulo2',
            'type'          => 'text',
            'instructions'  => 'Parte verde da 2ª linha (vem após "e ", que é fixo).',
            'default_value' => 'gestão de sistemas.',
        ],
        [
            'key'           => 'field_ecojob_operacao_intro',
            'label'         => 'Texto de apresentação',
            'name'          => 'ecojob_operacao_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Atuamos na operação assistida, supervisão técnica e gestão de sistemas de saneamento e recursos hídricos, promovendo maior confiabilidade, eficiência e controle por meio do acompanhamento contínuo dos processos e indicadores de gestão.',
        ],
        [
            'key'           => 'field_ecojob_oper_card1_titulo',
            'label'         => 'Card 1 — título',
            'name'          => 'ecojob_oper_card1_titulo',
            'type'          => 'text',
            'default_value' => 'Estações de Tratamento de Água (ETAs) e de Esgoto (ETEs)',
        ],
        [
            'key'           => 'field_ecojob_oper_card1_desc',
            'label'         => 'Card 1 — descrição',
            'name'          => 'ecojob_oper_card1_desc',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Acompanhamento operacional das unidades, controle de processos, gestão de indicadores de desempenho, elaboração de relatórios técnicos e apoio às atividades de manutenção, zeladoria e conservação das instalações, contribuindo para a eficiência e a confiabilidade dos sistemas.',
        ],
        [
            'key'           => 'field_ecojob_oper_card2_titulo',
            'label'         => 'Card 2 — título',
            'name'          => 'ecojob_oper_card2_titulo',
            'type'          => 'text',
            'default_value' => 'Estações Elevatórias de Água, Esgoto e Drenagem',
        ],
        [
            'key'           => 'field_ecojob_oper_card2_desc',
            'label'         => 'Card 2 — descrição',
            'name'          => 'ecojob_oper_card2_desc',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Supervisão operacional de estações elevatórias, acompanhando o desempenho dos equipamentos, conjuntos motobomba e sistemas auxiliares — com controle operacional, gestão de indicadores, avaliação do consumo energético e suporte à manutenção, visando aumentar a disponibilidade, a confiabilidade e a vida útil dos ativos.',
        ],

        [ 'key' => 'tab_ecojob_plataforma', 'label' => 'Plataforma COI 4.0', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_plat_chip',
            'label'         => 'Rótulo (topo)',
            'name'          => 'ecojob_plat_chip',
            'type'          => 'text',
            'default_value' => 'Plataforma · COI 4.0',
        ],
        [
            'key'           => 'field_ecojob_plat_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_plat_titulo1',
            'type'          => 'text',
            'default_value' => 'Plataforma de Gestão',
        ],
        [
            'key'           => 'field_ecojob_plat_titulo2',
            'label'         => 'Título — linha 2',
            'name'          => 'ecojob_plat_titulo2',
            'type'          => 'text',
            'default_value' => 'Inteligente Ecojob.',
        ],
        [
            'key'           => 'field_ecojob_plat_frase1',
            'label'         => 'Frase lateral — linha 1',
            'name'          => 'ecojob_plat_frase1',
            'type'          => 'text',
            'default_value' => 'O futuro da infraestrutura',
        ],
        [
            'key'           => 'field_ecojob_plat_frase2',
            'label'         => 'Frase lateral — destaque',
            'name'          => 'ecojob_plat_frase2',
            'type'          => 'text',
            'instructions'  => 'Palavra destacada em verde-claro (vem após "é ", que é fixo).',
            'default_value' => 'digital.',
        ],
        [
            'key'           => 'field_ecojob_plataforma_texto1',
            'label'         => 'Texto principal (parágrafo 1)',
            'name'          => 'ecojob_plataforma_texto1',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Você pode usar <strong>negrito</strong> em HTML.',
            'default_value' => 'Mais do que monitorar, a Tecnologia Ecojob conecta dados, sistemas e operações em um único ambiente digital. Nossa plataforma <strong style="font-weight:700;">COI 4.0</strong> integra sensores, telemetria, comunicação via satélite, modelagem computacional, análise geoespacial e inteligência artificial para transformar grandes volumes de dados em conhecimento aplicável.',
        ],
        [
            'key'           => 'field_ecojob_plataforma_texto2',
            'label'         => 'Texto principal (parágrafo 2)',
            'name'          => 'ecojob_plataforma_texto2',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Com uma visão integrada e em tempo real dos sistemas, a tecnologia permite identificar padrões, antecipar situações críticas, automatizar processos e ampliar a capacidade de gestão e controle das operações.',
        ],
        [
            'key'           => 'field_ecojob_plat_tec_label',
            'label'         => 'Rótulo — Tecnologias integradas',
            'name'          => 'ecojob_plat_tec_label',
            'type'          => 'text',
            'default_value' => 'Tecnologias integradas',
        ],
        [
            'key'           => 'field_ecojob_plat_tec1',
            'label'         => 'Tecnologia 1',
            'name'          => 'ecojob_plat_tec1',
            'type'          => 'text',
            'default_value' => 'Sensores',
        ],
        [
            'key'           => 'field_ecojob_plat_tec2',
            'label'         => 'Tecnologia 2',
            'name'          => 'ecojob_plat_tec2',
            'type'          => 'text',
            'default_value' => 'Telemetria',
        ],
        [
            'key'           => 'field_ecojob_plat_tec3',
            'label'         => 'Tecnologia 3',
            'name'          => 'ecojob_plat_tec3',
            'type'          => 'text',
            'default_value' => 'Comunicação via satélite',
        ],
        [
            'key'           => 'field_ecojob_plat_tec4',
            'label'         => 'Tecnologia 4',
            'name'          => 'ecojob_plat_tec4',
            'type'          => 'text',
            'default_value' => 'Modelagem computacional',
        ],
        [
            'key'           => 'field_ecojob_plat_tec5',
            'label'         => 'Tecnologia 5',
            'name'          => 'ecojob_plat_tec5',
            'type'          => 'text',
            'default_value' => 'Análise geoespacial',
        ],
        [
            'key'           => 'field_ecojob_plat_tec6',
            'label'         => 'Tecnologia 6',
            'name'          => 'ecojob_plat_tec6',
            'type'          => 'text',
            'default_value' => 'Inteligência artificial',
        ],

        [ 'key' => 'tab_ecojob_beneficios', 'label' => 'Benefícios', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_benef_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_benef_titulo1',
            'type'          => 'text',
            'default_value' => 'Benefícios da',
        ],
        [
            'key'           => 'field_ecojob_benef_titulo2',
            'label'         => 'Título — linha 2 (verde)',
            'name'          => 'ecojob_benef_titulo2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha, exibida em verde.',
            'default_value' => 'solução Ecojob.',
        ],
        [
            'key'           => 'field_ecojob_beneficios_intro',
            'label'         => 'Texto de apresentação',
            'name'          => 'ecojob_beneficios_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'A integração entre monitoramento inteligente, modelagem, análise de dados e supervisão operacional gera ganhos concretos para a gestão de sistemas ambientais e de saneamento.',
        ],
        [
            'key'           => 'field_ecojob_benef_card1_titulo',
            'label'         => 'Card 1 — título',
            'name'          => 'ecojob_benef_card1_titulo',
            'type'          => 'text',
            'default_value' => 'Maior eficiência operacional',
        ],
        [
            'key'           => 'field_ecojob_benef_card1_desc',
            'label'         => 'Card 1 — descrição',
            'name'          => 'ecojob_benef_card1_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Redução da sobrecarga dos sistemas, otimização dos processos de tratamento e melhor utilização dos recursos disponíveis.',
        ],
        [
            'key'           => 'field_ecojob_benef_card2_titulo',
            'label'         => 'Card 2 — título',
            'name'          => 'ecojob_benef_card2_titulo',
            'type'          => 'text',
            'default_value' => 'Redução de custos',
        ],
        [
            'key'           => 'field_ecojob_benef_card2_desc',
            'label'         => 'Card 2 — descrição',
            'name'          => 'ecojob_benef_card2_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Direcionamento mais preciso das equipes de campo, diminuição de intervenções emergenciais e otimização das atividades de operação e manutenção.',
        ],
        [
            'key'           => 'field_ecojob_benef_card3_titulo',
            'label'         => 'Card 3 — título',
            'name'          => 'ecojob_benef_card3_titulo',
            'type'          => 'text',
            'default_value' => 'Atuação preventiva',
        ],
        [
            'key'           => 'field_ecojob_benef_card3_desc',
            'label'         => 'Card 3 — descrição',
            'name'          => 'ecojob_benef_card3_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Identificação antecipada de anomalias, obstruções, contribuições irregulares e riscos de extravasamento, permitindo ações antes que os problemas ocorram.',
        ],
        [
            'key'           => 'field_ecojob_benef_card4_titulo',
            'label'         => 'Card 4 — título',
            'name'          => 'ecojob_benef_card4_titulo',
            'type'          => 'text',
            'default_value' => 'Proteção ambiental',
        ],
        [
            'key'           => 'field_ecojob_benef_card4_desc',
            'label'         => 'Card 4 — descrição',
            'name'          => 'ecojob_benef_card4_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Redução do lançamento de cargas poluidoras em corpos hídricos, melhoria da qualidade da água e mitigação de impactos ao meio ambiente.',
        ],
        [
            'key'           => 'field_ecojob_benef_card5_titulo',
            'label'         => 'Card 5 — título',
            'name'          => 'ecojob_benef_card5_titulo',
            'type'          => 'text',
            'default_value' => 'Planejamento baseado em dados',
        ],
        [
            'key'           => 'field_ecojob_benef_card5_desc',
            'label'         => 'Card 5 — descrição',
            'name'          => 'ecojob_benef_card5_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Análise de tendências, identificação de áreas críticas e priorização de investimentos e intervenções com maior assertividade.',
        ],
        [
            'key'           => 'field_ecojob_benef_card6_titulo',
            'label'         => 'Card 6 — título',
            'name'          => 'ecojob_benef_card6_titulo',
            'type'          => 'text',
            'default_value' => 'Maior segurança e confiabilidade',
        ],
        [
            'key'           => 'field_ecojob_benef_card6_desc',
            'label'         => 'Card 6 — descrição',
            'name'          => 'ecojob_benef_card6_desc',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Monitoramento contínuo, geração de alertas e suporte à tomada de decisão para uma gestão mais eficiente e resiliente.',
        ],
        [
            'key'           => 'field_ecojob_preditiva_titulo',
            'label'         => 'Destaque "Inteligência preditiva" — título',
            'name'          => 'ecojob_preditiva_titulo',
            'type'          => 'text',
            'default_value' => 'Inteligência preditiva',
        ],
        [
            'key'           => 'field_ecojob_preditiva_texto',
            'label'         => 'Texto do destaque "Inteligência preditiva"',
            'name'          => 'ecojob_preditiva_texto',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Você pode usar <strong>negrito</strong> em HTML.',
            'default_value' => 'Redes de distribuição, estações de tratamento e elevatórias passam a contar com um <strong style="color:#fff;font-weight:700;">gêmeo digital</strong>, que reproduz seu comportamento operacional e permite simular cenários, antecipar falhas e apoiar decisões de forma mais rápida e segura.',
        ],

        [ 'key' => 'tab_ecojob_cta', 'label' => 'Chamada final', 'type' => 'tab' ],
        [
            'key'           => 'field_ecojob_cta_titulo1',
            'label'         => 'Título — linha 1',
            'name'          => 'ecojob_cta_titulo1',
            'type'          => 'text',
            'default_value' => 'Solicite um',
        ],
        [
            'key'           => 'field_ecojob_cta_titulo2',
            'label'         => 'Título — linha 2',
            'name'          => 'ecojob_cta_titulo2',
            'type'          => 'text',
            'default_value' => 'diagnóstico Ecojob',
        ],
        [
            'key'           => 'field_ecojob_cta_titulo3',
            'label'         => 'Título — linha 3 (verde, itálico)',
            'name'          => 'ecojob_cta_titulo3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha, exibida em verde itálico.',
            'default_value' => 'para sua operação.',
        ],
        [
            'key'           => 'field_ecojob_cta_botao',
            'label'         => 'Rótulo do botão principal',
            'name'          => 'ecojob_cta_botao',
            'type'          => 'text',
            'instructions'  => 'Texto do botão. O telefone abaixo é dado de contato e não é editável aqui.',
            'default_value' => 'Solicitar proposta',
        ],

    ],
    'location' => [ [ [
        'param'    => 'page',
        'operator' => '==',
        'value'    => 8,
    ] ] ],
    'menu_order'            => 0,
    'position'              => 'normal',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
] );
