<?php
/**
 * Campos editáveis da HOME (front-page.php).
 * Organizados em abas para o painel ficar limpo. Cada campo já vem
 * preenchido com o texto atual (default_value), então o cliente vê o
 * conteúdo de hoje e só edita o que quiser.
 */
if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

acf_add_local_field_group( [
    'key'    => 'group_home',
    'title'  => 'Conteúdo da Home',
    'fields' => [

        /* ───────────────────────── TOPO ───────────────────────── */
        [ 'key' => 'tab_home_topo', 'label' => 'Topo', 'type' => 'tab' ],
        [
            'key'           => 'field_home_hero_l1',
            'label'         => 'Título — linha 1',
            'name'          => 'home_hero_l1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título principal do topo.',
            'default_value' => 'Engenharia',
        ],
        [
            'key'           => 'field_home_hero_l2',
            'label'         => 'Título — linha 2',
            'name'          => 'home_hero_l2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título principal.',
            'default_value' => 'que move',
        ],
        [
            'key'           => 'field_home_hero_l3',
            'label'         => 'Título — linha 3 (verde, em destaque)',
            'name'          => 'home_hero_l3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha do título — fica em verde e negrito.',
            'default_value' => 'o futuro.',
        ],
        [
            'key'           => 'field_home_hero_sub',
            'label'         => 'Subtítulo do topo',
            'name'          => 'home_hero_sub',
            'type'          => 'textarea',
            'rows'          => 2,
            'instructions'  => 'Texto curto logo abaixo do título principal “Engenharia que move o futuro.”',
            'default_value' => 'Soluções de engenharia que transformam desafios operacionais em resultados duradouros.',
        ],
        [
            'key'           => 'field_home_hero_cta1',
            'label'         => 'Botão 1 (verde)',
            'name'          => 'home_hero_cta1',
            'type'          => 'text',
            'instructions'  => 'Rótulo do primeiro botão do topo.',
            'default_value' => 'Conheça os serviços',
        ],
        [
            'key'           => 'field_home_hero_cta2',
            'label'         => 'Botão 2 (contorno)',
            'name'          => 'home_hero_cta2',
            'type'          => 'text',
            'instructions'  => 'Rótulo do segundo botão do topo.',
            'default_value' => 'Solicitar proposta',
        ],

        /* ──────────────────────── ESTATÍSTICAS ──────────────────────── */
        [ 'key' => 'tab_home_stats', 'label' => 'Estatísticas', 'type' => 'tab' ],
        [
            'key'           => 'field_home_stat1_num',
            'label'         => 'Estatística 1 — número',
            'name'          => 'home_stat1_num',
            'type'          => 'text',
            'default_value' => '15.000',
        ],
        [
            'key'           => 'field_home_stat1_label',
            'label'         => 'Estatística 1 — rótulo',
            'name'          => 'home_stat1_label',
            'type'          => 'text',
            'default_value' => 'Vias pavimentadas',
        ],
        [
            'key'           => 'field_home_stat2_num',
            'label'         => 'Estatística 2 — número',
            'name'          => 'home_stat2_num',
            'type'          => 'text',
            'instructions'  => 'Apenas o número (o “+” e a palavra “anos” são fixos no layout).',
            'default_value' => '4.000',
        ],
        [
            'key'           => 'field_home_stat2_unit',
            'label'         => 'Estatística 2 — unidade',
            'name'          => 'home_stat2_unit',
            'type'          => 'text',
            'default_value' => 'km',
        ],
        [
            'key'           => 'field_home_stat2_label',
            'label'         => 'Estatística 2 — rótulo',
            'name'          => 'home_stat2_label',
            'type'          => 'text',
            'default_value' => 'Redes desobstruídas',
        ],
        [
            'key'           => 'field_home_stat3_num',
            'label'         => 'Estatística 3 — número',
            'name'          => 'home_stat3_num',
            'type'          => 'text',
            'default_value' => 'xx',
        ],
        [
            'key'           => 'field_home_stat3_unit',
            'label'         => 'Estatística 3 — unidade',
            'name'          => 'home_stat3_unit',
            'type'          => 'text',
            'default_value' => 'pontos',
        ],
        [
            'key'           => 'field_home_stat3_label',
            'label'         => 'Estatística 3 — rótulo',
            'name'          => 'home_stat3_label',
            'type'          => 'text',
            'default_value' => 'Monitoramento em operação',
        ],
        [
            'key'           => 'field_home_stat4_num',
            'label'         => 'Estatística 4 — número',
            'name'          => 'home_stat4_num',
            'type'          => 'text',
            'default_value' => '160.000',
        ],
        [
            'key'           => 'field_home_stat4_unit',
            'label'         => 'Estatística 4 — unidade',
            'name'          => 'home_stat4_unit',
            'type'          => 'text',
            'default_value' => 'm',
        ],
        [
            'key'           => 'field_home_stat4_label',
            'label'         => 'Estatística 4 — rótulo',
            'name'          => 'home_stat4_label',
            'type'          => 'text',
            'default_value' => 'Redes inspecionadas por CFTV',
        ],

        /* ──────────────────────── SERVIÇOS ──────────────────────── */
        [ 'key' => 'tab_home_serv', 'label' => 'Serviços', 'type' => 'tab' ],
        [
            'key'           => 'field_home_serv_tit_l1',
            'label'         => 'Título — linha 1',
            'name'          => 'home_serv_tit_l1',
            'type'          => 'text',
            'instructions'  => 'A palavra “frentes” fica em verde (estilo fixo no layout).',
            'default_value' => 'Diversas frentes,',
        ],
        [
            'key'           => 'field_home_serv_tit_l2',
            'label'         => 'Título — linha 2',
            'name'          => 'home_serv_tit_l2',
            'type'          => 'text',
            'default_value' => 'uma engenharia',
        ],
        [
            'key'           => 'field_home_serv_tit_l3',
            'label'         => 'Título — linha 3 (cinza, itálico)',
            'name'          => 'home_serv_tit_l3',
            'type'          => 'text',
            'default_value' => 'que entrega soluções.',
        ],
        [
            'key'           => 'field_home_serv_intro',
            'label'         => 'Texto de apresentação dos serviços',
            'name'          => 'home_serv_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Combinamos expertise técnica, equipamentos especializados e processos de engenharia auditáveis para garantir qualidade, eficiência e resultados consistentes.',
        ],
        [
            'key'           => 'field_home_serv_link',
            'label'         => 'Link abaixo do texto',
            'name'          => 'home_serv_link',
            'type'          => 'text',
            'default_value' => 'Índice completo de serviços',
        ],

        // Card 1 — Infraestrutura
        [
            'key'           => 'field_home_serv1_titulo',
            'label'         => 'Card 1 — Título',
            'name'          => 'home_serv1_titulo',
            'type'          => 'text',
            'default_value' => 'Infraestrutura',
        ],
        [
            'key'           => 'field_home_serv1_meta',
            'label'         => 'Card 1 — Subtítulo (linha cinza)',
            'name'          => 'home_serv1_meta',
            'type'          => 'text',
            'default_value' => 'Obra · Recuperação · Pavimentação',
        ],
        [
            'key'           => 'field_home_serv1_itens',
            'label'         => 'Card 1 — Itens da lista',
            'name'          => 'home_serv1_itens',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Um item por linha.',
            'default_value' => "Obras e recuperação estrutural\nRodovias, vias vicinais e pontes\nPavimentação — Usina Móvel RAP\nSaneamento e drenagem",
        ],

        // Card 2 — Zeladoria
        [
            'key'           => 'field_home_serv2_titulo',
            'label'         => 'Card 2 — Título',
            'name'          => 'home_serv2_titulo',
            'type'          => 'text',
            'default_value' => 'Zeladoria e Manutenção de Ativos',
        ],
        [
            'key'           => 'field_home_serv2_meta',
            'label'         => 'Card 2 — Subtítulo (linha cinza)',
            'name'          => 'home_serv2_meta',
            'type'          => 'text',
            'default_value' => 'Limpeza · Redes · Áreas verdes',
        ],
        [
            'key'           => 'field_home_serv2_itens',
            'label'         => 'Card 2 — Itens da lista',
            'name'          => 'home_serv2_itens',
            'type'          => 'textarea',
            'rows'          => 5,
            'instructions'  => 'Um item por linha.',
            'default_value' => "Varrição e limpeza urbana\nManutenção de redes de esgoto\nManutenção de galerias de águas pluviais\nManutenção de vias públicas\nConservação de áreas verdes",
        ],

        // Card 3 — Predial
        [
            'key'           => 'field_home_serv3_titulo',
            'label'         => 'Card 3 — Título',
            'name'          => 'home_serv3_titulo',
            'type'          => 'text',
            'default_value' => 'Engenharia Predial',
        ],
        [
            'key'           => 'field_home_serv3_meta',
            'label'         => 'Card 3 — Subtítulo (linha cinza)',
            'name'          => 'home_serv3_meta',
            'type'          => 'text',
            'default_value' => 'Reforma · Sistemas · Manutenção',
        ],
        [
            'key'           => 'field_home_serv3_itens',
            'label'         => 'Card 3 — Itens da lista',
            'name'          => 'home_serv3_itens',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Um item por linha.',
            'default_value' => "Reformas e ampliações\nSistemas elétricos e hidráulicos\nManutenção geral programada",
        ],

        // Card 4 — Ambiental / Ecojob
        [
            'key'           => 'field_home_serv4_titulo',
            'label'         => 'Card 4 — Título',
            'name'          => 'home_serv4_titulo',
            'type'          => 'text',
            'instructions'  => 'O selo “/ Ecojob” ao lado é fixo no layout.',
            'default_value' => 'Tecnologia Ambiental',
        ],
        [
            'key'           => 'field_home_serv4_meta',
            'label'         => 'Card 4 — Subtítulo (linha cinza)',
            'name'          => 'home_serv4_meta',
            'type'          => 'text',
            'default_value' => 'Monitoramento · ETA / ETE · Diagnóstico',
        ],
        [
            'key'           => 'field_home_serv4_itens',
            'label'         => 'Card 4 — Itens da lista',
            'name'          => 'home_serv4_itens',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Um item por linha.',
            'default_value' => "Monitoramento de córregos, rios, canais e balneabilidade\nMonitoramento de sistemas de drenagem\nSistemas de esgotamento sanitário\nOperação assistida de ETAs e ETEs",
        ],
        [
            'key'           => 'field_home_serv_cta',
            'label'         => 'Rótulo do botão dos cards',
            'name'          => 'home_serv_cta',
            'type'          => 'text',
            'instructions'  => 'Texto do botão repetido em cada card (ex.: “Ver área”).',
            'default_value' => 'Ver área',
        ],

        /* ──────────────────────── ÁREAS DE ATUAÇÃO ──────────────────────── */
        [ 'key' => 'tab_home_areas', 'label' => 'Áreas de atuação', 'type' => 'tab' ],
        [
            'key'           => 'field_home_areas_tit_l1',
            'label'         => 'Título — linha 1',
            'name'          => 'home_areas_tit_l1',
            'type'          => 'text',
            'default_value' => 'Áreas de',
        ],
        [
            'key'           => 'field_home_areas_tit_l2',
            'label'         => 'Título — linha 2 (verde, itálico)',
            'name'          => 'home_areas_tit_l2',
            'type'          => 'text',
            'default_value' => 'atuação.',
        ],
        [
            'key'           => 'field_home_areas_intro',
            'label'         => 'Texto das áreas de atuação',
            'name'          => 'home_areas_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Da recuperação de pontes ao saneamento, da drenagem à tecnologia ambiental — engenharia aplicada em campo, em diferentes frentes.',
        ],

        // Mosaico — 6 tiles (título + legenda)
        [
            'key'           => 'field_home_mos1_titulo',
            'label'         => 'Mosaico 1 — Título',
            'name'          => 'home_mos1_titulo',
            'type'          => 'text',
            'default_value' => 'Pontes e viadutos',
        ],
        [
            'key'           => 'field_home_mos1_legenda',
            'label'         => 'Mosaico 1 — Legenda',
            'name'          => 'home_mos1_legenda',
            'type'          => 'text',
            'default_value' => 'Mobilidade · Recuperação',
        ],
        [
            'key'           => 'field_home_mos2_titulo',
            'label'         => 'Mosaico 2 — Título',
            'name'          => 'home_mos2_titulo',
            'type'          => 'text',
            'default_value' => 'Pavimentação',
        ],
        [
            'key'           => 'field_home_mos2_legenda',
            'label'         => 'Mosaico 2 — Legenda',
            'name'          => 'home_mos2_legenda',
            'type'          => 'text',
            'default_value' => 'Usina Móvel RAP',
        ],
        [
            'key'           => 'field_home_mos3_titulo',
            'label'         => 'Mosaico 3 — Título',
            'name'          => 'home_mos3_titulo',
            'type'          => 'text',
            'default_value' => 'Saneamento',
        ],
        [
            'key'           => 'field_home_mos3_legenda',
            'label'         => 'Mosaico 3 — Legenda',
            'name'          => 'home_mos3_legenda',
            'type'          => 'text',
            'default_value' => 'Redes de água e esgoto',
        ],
        [
            'key'           => 'field_home_mos4_titulo',
            'label'         => 'Mosaico 4 — Título',
            'name'          => 'home_mos4_titulo',
            'type'          => 'text',
            'default_value' => 'Drenagem',
        ],
        [
            'key'           => 'field_home_mos4_legenda',
            'label'         => 'Mosaico 4 — Legenda',
            'name'          => 'home_mos4_legenda',
            'type'          => 'text',
            'default_value' => 'Águas pluviais',
        ],
        [
            'key'           => 'field_home_mos5_titulo',
            'label'         => 'Mosaico 5 — Título',
            'name'          => 'home_mos5_titulo',
            'type'          => 'text',
            'default_value' => 'Zeladoria e manutenção',
        ],
        [
            'key'           => 'field_home_mos5_legenda',
            'label'         => 'Mosaico 5 — Legenda',
            'name'          => 'home_mos5_legenda',
            'type'          => 'text',
            'default_value' => 'Redes e ativos urbanos',
        ],
        [
            'key'           => 'field_home_mos6_titulo',
            'label'         => 'Mosaico 6 — Título',
            'name'          => 'home_mos6_titulo',
            'type'          => 'text',
            'default_value' => 'Tecnologia ambiental',
        ],
        [
            'key'           => 'field_home_mos6_legenda',
            'label'         => 'Mosaico 6 — Legenda',
            'name'          => 'home_mos6_legenda',
            'type'          => 'text',
            'default_value' => 'Plataforma Ecojob',
        ],

        /* ──────────────────────── SOBRE ──────────────────────── */
        [ 'key' => 'tab_home_sobre', 'label' => 'Sobre', 'type' => 'tab' ],
        [
            'key'           => 'field_home_sobre_tit_l1',
            'label'         => 'Título — linha 1',
            'name'          => 'home_sobre_tit_l1',
            'type'          => 'text',
            'default_value' => 'História, técnica',
        ],
        [
            'key'           => 'field_home_sobre_tit_l2',
            'label'         => 'Título — linha 2',
            'name'          => 'home_sobre_tit_l2',
            'type'          => 'text',
            'instructions'  => 'A palavra “compromisso” fica em verde (estilo fixo no layout).',
            'default_value' => 'e compromisso',
        ],
        [
            'key'           => 'field_home_sobre_tit_l3',
            'label'         => 'Título — linha 3 (cinza, itálico)',
            'name'          => 'home_sobre_tit_l3',
            'type'          => 'text',
            'default_value' => 'com o futuro.',
        ],
        [
            'key'           => 'field_home_sobre_intro',
            'label'         => 'Texto institucional (missão)',
            'name'          => 'home_sobre_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Nossa missão é entregar obras e serviços de alta qualidade, com tecnologia própria e metodologias exclusivas desenvolvidas ao longo de décadas de operação direta em campo.',
        ],
        // Selos (3 colunas)
        [
            'key'           => 'field_home_sobre_b1_num',
            'label'         => 'Selo 1 — número',
            'name'          => 'home_sobre_b1_num',
            'type'          => 'text',
            'default_value' => '1981',
        ],
        [
            'key'           => 'field_home_sobre_b1_label',
            'label'         => 'Selo 1 — rótulo',
            'name'          => 'home_sobre_b1_label',
            'type'          => 'text',
            'default_value' => 'Fundação',
        ],
        [
            'key'           => 'field_home_sobre_b2_num',
            'label'         => 'Selo 2 — número/sigla',
            'name'          => 'home_sobre_b2_num',
            'type'          => 'text',
            'default_value' => 'SP',
        ],
        [
            'key'           => 'field_home_sobre_b2_label',
            'label'         => 'Selo 2 — rótulo',
            'name'          => 'home_sobre_b2_label',
            'type'          => 'text',
            'default_value' => 'Sede · Tamboré',
        ],
        [
            'key'           => 'field_home_sobre_b3_num',
            'label'         => 'Selo 3 — número/sigla',
            'name'          => 'home_sobre_b3_num',
            'type'          => 'text',
            'default_value' => 'PNQS',
        ],
        [
            'key'           => 'field_home_sobre_b3_label',
            'label'         => 'Selo 3 — rótulo',
            'name'          => 'home_sobre_b3_label',
            'type'          => 'text',
            'default_value' => 'Reconhecimento 2024',
        ],
        // Definições (dl)
        [
            'key'           => 'field_home_sobre_dt1',
            'label'         => 'Definição 1 — rótulo',
            'name'          => 'home_sobre_dt1',
            'type'          => 'text',
            'default_value' => 'Atuação',
        ],
        [
            'key'           => 'field_home_sobre_dd1',
            'label'         => 'Definição 1 — valor',
            'name'          => 'home_sobre_dd1',
            'type'          => 'text',
            'default_value' => 'Municípios · Empresas',
        ],
        [
            'key'           => 'field_home_sobre_dt2',
            'label'         => 'Definição 2 — rótulo',
            'name'          => 'home_sobre_dt2',
            'type'          => 'text',
            'default_value' => 'Plataforma ambiental',
        ],
        [
            'key'           => 'field_home_sobre_dd2',
            'label'         => 'Definição 2 — valor',
            'name'          => 'home_sobre_dd2',
            'type'          => 'text',
            'default_value' => 'Ecojob',
        ],
        [
            'key'           => 'field_home_sobre_cta',
            'label'         => 'Rótulo do botão',
            'name'          => 'home_sobre_cta',
            'type'          => 'text',
            'default_value' => 'Conheça nossa história',
        ],

        /* ──────────────────────── TECNOLOGIA / ECOJOB ──────────────────────── */
        [ 'key' => 'tab_home_tec', 'label' => 'Tecnologia / Ecojob', 'type' => 'tab' ],
        [
            'key'           => 'field_home_tec_tit_l1',
            'label'         => 'Título — linha 1',
            'name'          => 'home_tec_tit_l1',
            'type'          => 'text',
            'default_value' => 'Tecnologia',
        ],
        [
            'key'           => 'field_home_tec_tit_l2',
            'label'         => 'Título — linha 2 (em destaque)',
            'name'          => 'home_tec_tit_l2',
            'type'          => 'text',
            'default_value' => 'própria.',
        ],
        [
            'key'           => 'field_home_tec_intro',
            'label'         => 'Texto da seção de tecnologia',
            'name'          => 'home_tec_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'default_value' => 'Plataforma Ecojob de engenharia ambiental — sensoriamento, diagnóstico e operação em ciclo completo, desenvolvida pela engenharia interna ao longo de décadas de operação.',
        ],
        // Cartão Ecojob (coluna esquerda)
        [
            'key'           => 'field_home_tec_card_titulo',
            'label'         => 'Cartão Ecojob — Título',
            'name'          => 'home_tec_card_titulo',
            'type'          => 'text',
            'default_value' => 'Tecnologia Ambiental',
        ],
        [
            'key'           => 'field_home_tec_card_texto',
            'label'         => 'Cartão Ecojob — Descrição',
            'name'          => 'home_tec_card_texto',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Engenharia de alta performance para gestão de infraestrutura urbana e saneamento — diagnóstico, monitoramento e operação em ciclo único.',
        ],
        [
            'key'           => 'field_home_tec_card_itens',
            'label'         => 'Cartão Ecojob — Lista',
            'name'          => 'home_tec_card_itens',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Um item por linha.',
            'default_value' => "Engenharia diagnóstica\nEcossistema tecnológico\nQuatro domínios de atuação",
        ],
        [
            'key'           => 'field_home_tec_card_cta',
            'label'         => 'Cartão Ecojob — Botão',
            'name'          => 'home_tec_card_cta',
            'type'          => 'text',
            'default_value' => 'Conhecer Ecojob',
        ],
        // Quatro boxes (título + nota)
        [
            'key'           => 'field_home_tec_box1_titulo',
            'label'         => 'Box 1 — Título',
            'name'          => 'home_tec_box1_titulo',
            'type'          => 'text',
            'default_value' => 'Monitoramento de córregos, rios, canais e balneabilidade',
        ],
        [
            'key'           => 'field_home_tec_box1_nota',
            'label'         => 'Box 1 — Nota',
            'name'          => 'home_tec_box1_nota',
            'type'          => 'text',
            'default_value' => 'CONAMA 357/05',
        ],
        [
            'key'           => 'field_home_tec_box2_titulo',
            'label'         => 'Box 2 — Título',
            'name'          => 'home_tec_box2_titulo',
            'type'          => 'text',
            'default_value' => 'Monitoramento de sistemas de drenagem',
        ],
        [
            'key'           => 'field_home_tec_box2_nota',
            'label'         => 'Box 2 — Nota',
            'name'          => 'home_tec_box2_nota',
            'type'          => 'text',
            'default_value' => 'Sensores IoT · CCTV',
        ],
        [
            'key'           => 'field_home_tec_box3_titulo',
            'label'         => 'Box 3 — Título',
            'name'          => 'home_tec_box3_titulo',
            'type'          => 'text',
            'default_value' => 'Sistemas de esgotamento sanitário',
        ],
        [
            'key'           => 'field_home_tec_box3_nota',
            'label'         => 'Box 3 — Nota',
            'name'          => 'home_tec_box3_nota',
            'type'          => 'text',
            'default_value' => 'CONAMA 430/11',
        ],
        [
            'key'           => 'field_home_tec_box4_titulo',
            'label'         => 'Box 4 — Título',
            'name'          => 'home_tec_box4_titulo',
            'type'          => 'text',
            'default_value' => 'Operação assistida de ETAs e ETEs',
        ],
        [
            'key'           => 'field_home_tec_box4_nota',
            'label'         => 'Box 4 — Nota',
            'name'          => 'home_tec_box4_nota',
            'type'          => 'text',
            'default_value' => 'Operação · Otimização',
        ],
        [
            'key'           => 'field_home_tec_rodape',
            'label'         => 'Texto de rodapé (itálico)',
            'name'          => 'home_tec_rodape',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Complementado por Gestão e Planejamento (Novo Marco do Saneamento) + Diagnóstico e Prognóstico estratégico.',
        ],

        /* ──────────────────────── CONTATO ──────────────────────── */
        [ 'key' => 'tab_home_contato', 'label' => 'Contato', 'type' => 'tab' ],
        [
            'key'           => 'field_home_contato_tit_l1',
            'label'         => 'Título — linha 1',
            'name'          => 'home_contato_tit_l1',
            'type'          => 'text',
            'default_value' => 'Solicite',
        ],
        [
            'key'           => 'field_home_contato_tit_l2',
            'label'         => 'Título — linha 2',
            'name'          => 'home_contato_tit_l2',
            'type'          => 'text',
            'default_value' => 'sua proposta',
        ],
        [
            'key'           => 'field_home_contato_tit_l3',
            'label'         => 'Título — linha 3 (verde, itálico)',
            'name'          => 'home_contato_tit_l3',
            'type'          => 'text',
            'default_value' => 'técnica.',
        ],
        [
            'key'           => 'field_home_contato_intro',
            'label'         => 'Texto acima do formulário de contato',
            'name'          => 'home_contato_intro',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Nossa equipe está pronta para apresentar a solução ideal para o seu negócio.',
        ],
        // Rótulos dos blocos de contato (os dados em si serão globais depois)
        [
            'key'           => 'field_home_contato_lbl_tel',
            'label'         => 'Rótulo — Telefone',
            'name'          => 'home_contato_lbl_tel',
            'type'          => 'text',
            'default_value' => 'Telefone',
        ],
        [
            'key'           => 'field_home_contato_lbl_email',
            'label'         => 'Rótulo — E-mail',
            'name'          => 'home_contato_lbl_email',
            'type'          => 'text',
            'default_value' => 'E-mail comercial · Proposta técnica',
        ],
        [
            'key'           => 'field_home_contato_lbl_horario',
            'label'         => 'Rótulo — Horário',
            'name'          => 'home_contato_lbl_horario',
            'type'          => 'text',
            'default_value' => 'Horário de atendimento',
        ],
        [
            'key'           => 'field_home_contato_horario',
            'label'         => 'Horário de atendimento',
            'name'          => 'home_contato_horario',
            'type'          => 'text',
            'default_value' => 'Segunda a sexta · 9h às 18h',
        ],

    ],
    'location' => [ [ [
        'param'    => 'page_type',
        'operator' => '==',
        'value'    => 'front_page',
    ] ] ],
    'menu_order'            => 0,
    'position'              => 'normal',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
] );
