<?php
/**
 * Campos editáveis da página SERVIÇOS (page-servicos.php).
 * Organizados em abas por seção. Cada campo já vem preenchido com o
 * texto atual (default_value), então o cliente vê o conteúdo de hoje
 * e só edita o que quiser. Títulos estilizados, listas de cards,
 * chips e dados de contato continuam fixos no template.
 */
if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

acf_add_local_field_group( [
    'key'    => 'group_servicos',
    'title'  => 'Conteúdo: Serviços',
    'fields' => [

        /* ─── HERO / TÍTULOS GERAIS ─── */
        [ 'key' => 'tab_servicos_hero', 'label' => 'Topo / Abas', 'type' => 'tab' ],
        [
            'key'           => 'field_servicos_hero_l1',
            'label'         => 'Título do topo — linha 1',
            'name'          => 'servicos_hero_l1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título principal da página.',
            'default_value' => 'Diversas frentes,',
        ],
        [
            'key'           => 'field_servicos_hero_l2a',
            'label'         => 'Título do topo — linha 2 (início)',
            'name'          => 'servicos_hero_l2a',
            'type'          => 'text',
            'instructions'  => 'Segunda linha, antes da palavra em verde. Ex.: “uma ”.',
            'default_value' => 'uma ',
        ],
        [
            'key'           => 'field_servicos_hero_l2b',
            'label'         => 'Título do topo — linha 2 (palavra em verde)',
            'name'          => 'servicos_hero_l2b',
            'type'          => 'text',
            'instructions'  => 'Palavra destacada em verde na segunda linha.',
            'default_value' => 'engenharia',
        ],
        [
            'key'           => 'field_servicos_hero_l3',
            'label'         => 'Título do topo — linha 3 (itálico cinza)',
            'name'          => 'servicos_hero_l3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha do título, em itálico cinza.',
            'default_value' => 'que entrega soluções.',
        ],
        [
            'key'           => 'field_servicos_tab_infra',
            'label'         => 'Aba — Infraestrutura',
            'name'          => 'servicos_tab_infra',
            'type'          => 'text',
            'instructions'  => 'Rótulo da aba de navegação (barra fixa).',
            'default_value' => 'Infraestrutura',
        ],
        [
            'key'           => 'field_servicos_tab_zeladoria',
            'label'         => 'Aba — Zeladoria',
            'name'          => 'servicos_tab_zeladoria',
            'type'          => 'text',
            'instructions'  => 'Rótulo da aba de navegação (barra fixa).',
            'default_value' => 'Zeladoria e Manutenção de Ativos',
        ],
        [
            'key'           => 'field_servicos_tab_predial',
            'label'         => 'Aba — Engenharia Predial',
            'name'          => 'servicos_tab_predial',
            'type'          => 'text',
            'instructions'  => 'Rótulo da aba de navegação (barra fixa).',
            'default_value' => 'Engenharia Predial',
        ],
        [
            'key'           => 'field_servicos_tab_ambiental',
            'label'         => 'Aba — Tecnologia Ambiental',
            'name'          => 'servicos_tab_ambiental',
            'type'          => 'text',
            'instructions'  => 'Rótulo da aba de navegação (barra fixa).',
            'default_value' => 'Tecnologia Ambiental',
        ],

        /* ─── INFRAESTRUTURA ─── */
        [ 'key' => 'tab_servicos_infra', 'label' => 'Infraestrutura', 'type' => 'tab' ],
        [
            'key'           => 'field_servicos_infra_t1',
            'label'         => 'Título da seção — linha 1',
            'name'          => 'servicos_infra_t1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título da seção Infraestrutura.',
            'default_value' => 'Infraestrutura de mobilidade,',
        ],
        [
            'key'           => 'field_servicos_infra_t2',
            'label'         => 'Título da seção — linha 2 (itálico cinza)',
            'name'          => 'servicos_infra_t2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título, em itálico cinza.',
            'default_value' => 'recursos hídricos e saneamento.',
        ],
        [
            'key'           => 'field_servicos_infra_intro',
            'label'         => 'Texto de apresentação — Infraestrutura',
            'name'          => 'servicos_infra_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Parágrafo de introdução da seção Infraestrutura.',
            'default_value' => 'Atuamos no desenvolvimento e aprimoramento de sistemas e ativos de infraestrutura, contribuindo para a mobilidade, a gestão dos recursos hídricos e a universalização do saneamento por meio de soluções sustentáveis e de alto desempenho.',
        ],

        /* Subcategoria · Mobilidade */
        [
            'key'           => 'field_servicos_infra_sub_mobilidade',
            'label'         => 'Rótulo subcategoria — Mobilidade',
            'name'          => 'servicos_infra_sub_mobilidade',
            'type'          => 'text',
            'instructions'  => 'Rótulo da subcategoria.',
            'default_value' => 'Mobilidade',
        ],
        [
            'key'           => 'field_servicos_infra_rodovias_titulo',
            'label'         => 'Card Rodovias — título',
            'name'          => 'servicos_infra_rodovias_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Rodovias',
        ],
        [
            'key'           => 'field_servicos_infra_rodovias_meta',
            'label'         => 'Card Rodovias — legenda',
            'name'          => 'servicos_infra_rodovias_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Mobilidade · Segurança',
        ],
        [
            'key'           => 'field_servicos_infra_vicinais_titulo',
            'label'         => 'Card Vias vicinais — título',
            'name'          => 'servicos_infra_vicinais_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Vias vicinais',
        ],
        [
            'key'           => 'field_servicos_infra_vicinais_meta',
            'label'         => 'Card Vias vicinais — legenda',
            'name'          => 'servicos_infra_vicinais_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Estradas rurais · Acesso municipal',
        ],
        [
            'key'           => 'field_servicos_infra_pontes_titulo',
            'label'         => 'Card Pontes e viadutos — título',
            'name'          => 'servicos_infra_pontes_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Pontes e viadutos',
        ],
        [
            'key'           => 'field_servicos_infra_pontes_meta',
            'label'         => 'Card Pontes e viadutos — legenda',
            'name'          => 'servicos_infra_pontes_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Construção · Recuperação e reforço estrutural · Revitalização',
        ],

        /* Subcategoria · Pavimentação + RAP */
        [
            'key'           => 'field_servicos_infra_sub_pavimentacao',
            'label'         => 'Rótulo subcategoria — Pavimentação',
            'name'          => 'servicos_infra_sub_pavimentacao',
            'type'          => 'text',
            'instructions'  => 'Rótulo da subcategoria.',
            'default_value' => 'Pavimentação',
        ],
        [
            'key'           => 'field_servicos_rap_titulo_a',
            'label'         => 'RAP — título (parte 1)',
            'name'          => 'servicos_rap_titulo_a',
            'type'          => 'text',
            'instructions'  => 'Parte do título antes da sigla em verde. Ex.: “Usina Móvel ”.',
            'default_value' => 'Usina Móvel ',
        ],
        [
            'key'           => 'field_servicos_rap_titulo_b',
            'label'         => 'RAP — título (sigla em verde)',
            'name'          => 'servicos_rap_titulo_b',
            'type'          => 'text',
            'instructions'  => 'Sigla destacada em verde no título.',
            'default_value' => 'RAP',
        ],
        [
            'key'           => 'field_servicos_rap_texto',
            'label'         => 'Texto do destaque — Usina Móvel RAP',
            'name'          => 'servicos_rap_texto',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Descrição do bloco em destaque da Usina Móvel RAP.',
            'default_value' => 'Nosso grande diferencial é a utilização de usina móvel de RAP (Reclaimed Asphalt Pavement), que permite a reutilização de materiais, reduz custos e reforça nosso compromisso com a sustentabilidade.',
        ],
        [
            'key'           => 'field_servicos_rap_cta',
            'label'         => 'RAP — rótulo do botão',
            'name'          => 'servicos_rap_cta',
            'type'          => 'text',
            'instructions'  => 'Texto do link de ação do bloco RAP.',
            'default_value' => 'Solicitar viabilidade',
        ],
        [
            'key'           => 'field_servicos_rap_stat1_label',
            'label'         => 'RAP — rótulo da estatística 1',
            'name'          => 'servicos_rap_stat1_label',
            'type'          => 'text',
            'instructions'  => 'Rótulo acima do número “100%”.',
            'default_value' => 'Reaproveitamento de materiais',
        ],
        [
            'key'           => 'field_servicos_rap_stat1_num',
            'label'         => 'RAP — número da estatística 1',
            'name'          => 'servicos_rap_stat1_num',
            'type'          => 'text',
            'instructions'  => 'Número grande (sem o símbolo %, que é fixo).',
            'default_value' => '100',
        ],
        [
            'key'           => 'field_servicos_rap_stat2_label',
            'label'         => 'RAP — rótulo da estatística 2',
            'name'          => 'servicos_rap_stat2_label',
            'type'          => 'text',
            'instructions'  => 'Rótulo do segundo dado.',
            'default_value' => 'Operação',
        ],
        [
            'key'           => 'field_servicos_rap_stat2_valor',
            'label'         => 'RAP — valor da estatística 2',
            'name'          => 'servicos_rap_stat2_valor',
            'type'          => 'text',
            'instructions'  => 'Descrição do segundo dado.',
            'default_value' => 'Reciclagem in situ — sem transporte de fresado.',
        ],

        /* Subcategoria · Saneamento */
        [
            'key'           => 'field_servicos_infra_sub_saneamento',
            'label'         => 'Rótulo subcategoria — Saneamento',
            'name'          => 'servicos_infra_sub_saneamento',
            'type'          => 'text',
            'instructions'  => 'Rótulo da subcategoria.',
            'default_value' => 'Saneamento',
        ],
        [
            'key'           => 'field_servicos_saneamento_meta',
            'label'         => 'Saneamento — legenda',
            'name'          => 'servicos_saneamento_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda acima do texto (separar itens com “ · ”).',
            'default_value' => 'Redes de água · Esgoto',
        ],
        [
            'key'           => 'field_servicos_saneamento_texto',
            'label'         => 'Texto — Saneamento',
            'name'          => 'servicos_saneamento_texto',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Descrição da subcategoria Saneamento.',
            'default_value' => 'Desenvolvemos soluções de saneamento voltadas à implantação e aprimoramento de redes de água e esgoto, combinando engenharia, tecnologia e expertise operacional para fortalecer a infraestrutura e ampliar a eficiência dos sistemas.',
        ],

        /* Subcategoria · Drenagem */
        [
            'key'           => 'field_servicos_infra_sub_drenagem',
            'label'         => 'Rótulo subcategoria — Drenagem',
            'name'          => 'servicos_infra_sub_drenagem',
            'type'          => 'text',
            'instructions'  => 'Rótulo da subcategoria.',
            'default_value' => 'Drenagem',
        ],
        [
            'key'           => 'field_servicos_drenagem_meta',
            'label'         => 'Drenagem — legenda',
            'name'          => 'servicos_drenagem_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda acima do texto (separar itens com “ · ”).',
            'default_value' => 'Águas pluviais · Prevenção de alagamentos',
        ],
        [
            'key'           => 'field_servicos_drenagem_texto',
            'label'         => 'Texto — Drenagem',
            'name'          => 'servicos_drenagem_texto',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Descrição da subcategoria Drenagem.',
            'default_value' => 'Atuamos na implantação e modernização de sistemas de drenagem, promovendo o adequado escoamento das águas pluviais e o desempenho da infraestrutura urbana.',
        ],

        /* ─── ZELADORIA ─── */
        [ 'key' => 'tab_servicos_zeladoria', 'label' => 'Zeladoria', 'type' => 'tab' ],
        [
            'key'           => 'field_servicos_zeladoria_t1',
            'label'         => 'Título da seção — linha 1',
            'name'          => 'servicos_zeladoria_t1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título da seção Zeladoria.',
            'default_value' => 'Zeladoria e',
        ],
        [
            'key'           => 'field_servicos_zeladoria_t2',
            'label'         => 'Título da seção — linha 2 (itálico cinza)',
            'name'          => 'servicos_zeladoria_t2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título, em itálico cinza.',
            'default_value' => 'manutenção de ativos.',
        ],
        [
            'key'           => 'field_servicos_zeladoria_intro',
            'label'         => 'Texto de apresentação — Zeladoria',
            'name'          => 'servicos_zeladoria_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'instructions'  => 'Parágrafo de introdução da seção Zeladoria e Manutenção de Ativos.',
            'default_value' => 'Atuamos na conservação e manutenção contínua dos ambientes atendidos, promovendo qualidade, funcionalidade e bem-estar no dia a dia.',
        ],
        [
            'key'           => 'field_servicos_zel_c1_titulo',
            'label'         => 'Card 1 — título',
            'name'          => 'servicos_zel_c1_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Varrição e limpeza urbana',
        ],
        [
            'key'           => 'field_servicos_zel_c1_meta',
            'label'         => 'Card 1 — legenda',
            'name'          => 'servicos_zel_c1_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Alto padrão de eficiência',
        ],
        [
            'key'           => 'field_servicos_zel_c2_titulo',
            'label'         => 'Card 2 — título',
            'name'          => 'servicos_zel_c2_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Manutenção preventiva e corretiva em redes de esgoto',
        ],
        [
            'key'           => 'field_servicos_zel_c2_meta',
            'label'         => 'Card 2 — legenda',
            'name'          => 'servicos_zel_c2_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Prevenção de entupimentos e extravasamentos · Tecnologia de ponta',
        ],
        [
            'key'           => 'field_servicos_zel_c3_titulo',
            'label'         => 'Card 3 — título',
            'name'          => 'servicos_zel_c3_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Manutenção preventiva e corretiva em galerias de águas pluviais',
        ],
        [
            'key'           => 'field_servicos_zel_c3_meta',
            'label'         => 'Card 3 — legenda',
            'name'          => 'servicos_zel_c3_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Escoamento correto das águas da chuva · Prevenção de alagamentos',
        ],
        [
            'key'           => 'field_servicos_zel_c4_titulo',
            'label'         => 'Card 4 — título',
            'name'          => 'servicos_zel_c4_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Manutenção de vias públicas',
        ],
        [
            'key'           => 'field_servicos_zel_c4_meta',
            'label'         => 'Card 4 — legenda',
            'name'          => 'servicos_zel_c4_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Mobilidade · Segurança',
        ],
        [
            'key'           => 'field_servicos_zel_c5_titulo',
            'label'         => 'Card 5 — título',
            'name'          => 'servicos_zel_c5_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Áreas verdes',
        ],
        [
            'key'           => 'field_servicos_zel_c5_meta',
            'label'         => 'Card 5 — legenda',
            'name'          => 'servicos_zel_c5_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Conservação · Preservação ambiental',
        ],

        /* ─── PREDIAL ─── */
        [ 'key' => 'tab_servicos_predial', 'label' => 'Engenharia Predial', 'type' => 'tab' ],
        [
            'key'           => 'field_servicos_predial_t1',
            'label'         => 'Título da seção — linha 1',
            'name'          => 'servicos_predial_t1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título da seção.',
            'default_value' => 'Engenharia',
        ],
        [
            'key'           => 'field_servicos_predial_t2',
            'label'         => 'Título da seção — linha 2 (verde)',
            'name'          => 'servicos_predial_t2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título, destacada em verde.',
            'default_value' => 'predial.',
        ],
        [
            'key'           => 'field_servicos_predial_intro',
            'label'         => 'Texto de apresentação — Engenharia Predial',
            'name'          => 'servicos_predial_intro',
            'type'          => 'textarea',
            'rows'          => 4,
            'instructions'  => 'Parágrafo de introdução da seção Engenharia Predial.',
            'default_value' => 'Atuamos na execução de serviços de engenharia predial que promovem a adequação, modernização e valorização das edificações, combinando qualidade técnica, segurança e eficiência operacional.',
        ],
        [
            'key'           => 'field_servicos_pred_c1_titulo',
            'label'         => 'Card 1 — título',
            'name'          => 'servicos_pred_c1_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Reformas e ampliações',
        ],
        [
            'key'           => 'field_servicos_pred_c1_meta',
            'label'         => 'Card 1 — legenda',
            'name'          => 'servicos_pred_c1_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Adaptação · Eficiência · Qualidade',
        ],
        [
            'key'           => 'field_servicos_pred_c2_titulo',
            'label'         => 'Card 2 — título',
            'name'          => 'servicos_pred_c2_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Manutenção predial geral',
        ],
        [
            'key'           => 'field_servicos_pred_c2_meta',
            'label'         => 'Card 2 — legenda',
            'name'          => 'servicos_pred_c2_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Preventiva · Corretiva',
        ],
        [
            'key'           => 'field_servicos_pred_c3_titulo',
            'label'         => 'Card 3 — título',
            'name'          => 'servicos_pred_c3_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Modernização de sistemas elétricos e hidráulicos',
        ],
        [
            'key'           => 'field_servicos_pred_c3_meta',
            'label'         => 'Card 3 — legenda',
            'name'          => 'servicos_pred_c3_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Segurança · Economia · Normas técnicas',
        ],

        /* ─── AMBIENTAL / ECOJOB ─── */
        [ 'key' => 'tab_servicos_ambiental', 'label' => 'Tecnologia Ambiental', 'type' => 'tab' ],
        [
            'key'           => 'field_servicos_ambiental_t1',
            'label'         => 'Título da seção — linha 1 (fina)',
            'name'          => 'servicos_ambiental_t1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título (peso fino).',
            'default_value' => 'Tecnologia',
        ],
        [
            'key'           => 'field_servicos_ambiental_t2',
            'label'         => 'Título da seção — linha 2 (negrito)',
            'name'          => 'servicos_ambiental_t2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título (peso forte).',
            'default_value' => 'ambiental.',
        ],
        [
            'key'           => 'field_servicos_ambiental_intro',
            'label'         => 'Texto institucional — Ecojob',
            'name'          => 'servicos_ambiental_intro',
            'type'          => 'wysiwyg',
            'tabs'          => 'visual',
            'media_upload'  => 0,
            'instructions'  => 'Parágrafo institucional da Ecojob (aceita negrito).',
            'default_value' => 'A <strong style="font-weight:700;">Ecojob</strong> é especializada em engenharia de alta performance para a gestão de infraestrutura urbana e saneamento. Nosso diferencial é a entrega de uma solução de ciclo completo: unimos o diagnóstico técnico, o monitoramento tecnológico de última geração e a zeladoria operacional para garantir máxima eficiência, resiliência urbana e conformidade legal.',
        ],
        [
            'key'           => 'field_servicos_ambiental_cta',
            'label'         => 'Chamada acima do botão — Ecojob',
            'name'          => 'servicos_ambiental_cta',
            'type'          => 'wysiwyg',
            'tabs'          => 'visual',
            'media_upload'  => 0,
            'instructions'  => 'Frase de chamada antes do botão “Conhecer Ecojob” (aceita destaque em cor).',
            'default_value' => 'Conheça a plataforma completa de engenharia ambiental Ecojob — <span style="color:#a8f0c4;font-weight:500;">sensoriamento, diagnóstico e operação</span> em ciclo único.',
        ],
        [
            'key'           => 'field_servicos_eco_btn',
            'label'         => 'Rótulo do botão — Conhecer Ecojob',
            'name'          => 'servicos_eco_btn',
            'type'          => 'text',
            'instructions'  => 'Texto do botão que leva à página Ecojob.',
            'default_value' => 'Conhecer Ecojob',
        ],

        /* Cards das 5 frentes Ecojob */
        [
            'key'           => 'field_servicos_eco_c1_titulo',
            'label'         => 'Frente 1 — título',
            'name'          => 'servicos_eco_c1_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Monitoramento de córregos, rios, canais e balneabilidade',
        ],
        [
            'key'           => 'field_servicos_eco_c1_meta',
            'label'         => 'Frente 1 — legenda',
            'name'          => 'servicos_eco_c1_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'CONAMA 357/05 · Sondas multiparamétricas',
        ],
        [
            'key'           => 'field_servicos_eco_c2_titulo',
            'label'         => 'Frente 2 — título',
            'name'          => 'servicos_eco_c2_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Monitoramento de sistemas de drenagem',
        ],
        [
            'key'           => 'field_servicos_eco_c2_meta',
            'label'         => 'Frente 2 — legenda',
            'name'          => 'servicos_eco_c2_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Sensores IoT · CCTV · Engenharia investigativa',
        ],
        [
            'key'           => 'field_servicos_eco_c3_titulo',
            'label'         => 'Frente 3 — título',
            'name'          => 'servicos_eco_c3_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Sistemas de esgotamento sanitário',
        ],
        [
            'key'           => 'field_servicos_eco_c3_meta',
            'label'         => 'Frente 3 — legenda',
            'name'          => 'servicos_eco_c3_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'CONAMA 430/11 · Separação absoluta',
        ],
        [
            'key'           => 'field_servicos_eco_c4_titulo',
            'label'         => 'Frente 4 — título',
            'name'          => 'servicos_eco_c4_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Operação assistida de ETAs e ETEs',
        ],
        [
            'key'           => 'field_servicos_eco_c4_meta',
            'label'         => 'Frente 4 — legenda',
            'name'          => 'servicos_eco_c4_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Operação · Conservação · Otimização',
        ],
        [
            'key'           => 'field_servicos_eco_c5_titulo',
            'label'         => 'Frente 5 — título',
            'name'          => 'servicos_eco_c5_titulo',
            'type'          => 'text',
            'instructions'  => 'Título do card.',
            'default_value' => 'Gestão, Diagnóstico e Prognóstico',
        ],
        [
            'key'           => 'field_servicos_eco_c5_meta',
            'label'         => 'Frente 5 — legenda',
            'name'          => 'servicos_eco_c5_meta',
            'type'          => 'text',
            'instructions'  => 'Legenda do card (separar itens com “ · ”).',
            'default_value' => 'Novo Marco do Saneamento · CID · CCTV robotizado',
        ],

        /* ─── CTA FINAL ─── */
        [ 'key' => 'tab_servicos_cta', 'label' => 'Chamada final', 'type' => 'tab' ],
        [
            'key'           => 'field_servicos_cta_t1',
            'label'         => 'Título — linha 1',
            'name'          => 'servicos_cta_t1',
            'type'          => 'text',
            'instructions'  => 'Primeira linha do título da chamada final.',
            'default_value' => 'Solicite proposta',
        ],
        [
            'key'           => 'field_servicos_cta_t2',
            'label'         => 'Título — linha 2',
            'name'          => 'servicos_cta_t2',
            'type'          => 'text',
            'instructions'  => 'Segunda linha do título.',
            'default_value' => 'ou fale com um',
        ],
        [
            'key'           => 'field_servicos_cta_t3',
            'label'         => 'Título — linha 3 (itálico claro)',
            'name'          => 'servicos_cta_t3',
            'type'          => 'text',
            'instructions'  => 'Terceira linha do título, em itálico claro.',
            'default_value' => 'especialista.',
        ],
        [
            'key'           => 'field_servicos_cta_btn',
            'label'         => 'Rótulo do botão — Solicitar proposta',
            'name'          => 'servicos_cta_btn',
            'type'          => 'text',
            'instructions'  => 'Texto do botão principal da chamada final.',
            'default_value' => 'Solicitar proposta',
        ],

    ],
    'location' => [ [ [
        'param'    => 'page',
        'operator' => '==',
        'value'    => 6,
    ] ] ],
    'menu_order'            => 0,
    'position'              => 'normal',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
] );
